export const FINANCE_CATALOG = [
	{ name: "read_instruments", surface: "intelligence", group: "read", fields: [] },
	{ name: "read_bars", surface: "intelligence", group: "read", fields: ["instrument_id"] },
	{ name: "read_screeners", surface: "intelligence", group: "read", fields: [] },
	{ name: "read_strategies", surface: "intelligence", group: "read", fields: [] },
	{ name: "read_books", surface: "intelligence", group: "read", fields: [] },
	{ name: "read_performance", surface: "intelligence", group: "read", fields: [] },
	{ name: "read_policies", surface: "governance", group: "read", fields: [] },
	{ name: "read_evaluations", surface: "governance", group: "read", fields: [] },
	{ name: "read_approvals", surface: "governance", group: "read", fields: [] },
	{ name: "read_dispatches", surface: "safety", group: "read", fields: [] },
	{ name: "read_observed_results", surface: "safety", group: "read", fields: [] },
	{ name: "read_limits", surface: "safety", group: "read", fields: [] },
	{ name: "read_kill_switches", surface: "safety", group: "read", fields: [] },
	{ name: "create_instrument", surface: "intelligence", group: "create", fields: ["organization_id", "symbol", "name"] },
	{ name: "replace_market_bars", surface: "intelligence", group: "create", fields: ["instrument_id", "bars"] },
	{ name: "create_screener", surface: "intelligence", group: "create", fields: ["organization_id", "name", "spec"] },
	{ name: "run_screener", surface: "intelligence", group: "run", fields: ["screener_id"] },
	{ name: "capture_snapshot", surface: "intelligence", group: "run", fields: ["screener_id", "as_of"] },
	{ name: "compile_strategy", surface: "copilot", group: "validate", fields: ["candidate"] },
	{ name: "create_strategy", surface: "intelligence", group: "create", fields: ["instrument_id", "name", "spec"] },
	{ name: "validate_strategy", surface: "intelligence", group: "validate", fields: ["strategy_id"] },
	{ name: "run_snapshot_strategy", surface: "intelligence", group: "run", fields: ["snapshot_id", "strategy_id"] },
	{ name: "run_spec_backtest", surface: "intelligence", group: "run", fields: ["strategy_id"] },
	{ name: "apply_paper_book", surface: "intelligence", group: "run", fields: ["portfolio_id", "book_id"] },
	{ name: "create_risk_policy", surface: "governance", group: "create", fields: ["organization_id", "policy"] },
	{ name: "replace_risk_policy", surface: "governance", group: "create", fields: ["policy_id", "policy"] },
	{ name: "evaluate_risk_policy", surface: "governance", group: "run", fields: ["policy_id", "book_id"] },
	{ name: "approve_strategy", surface: "governance", group: "approve", fields: ["book_id"] },
	{ name: "create_order_intent", surface: "safety", group: "create", fields: ["approval_id"] },
	{ name: "recheck_order_intent", surface: "safety", group: "run", fields: ["intent_id"] },
	{ name: "authorize_order_intent", surface: "safety", group: "approve", fields: ["intent_id"] },
	{ name: "create_execution_contract", surface: "safety", group: "create", fields: ["authorization_id"] },
	{ name: "record_production_authorization", surface: "safety", group: "record", fields: ["contract_id"] },
	{ name: "cancel_production_authorization", surface: "safety", group: "approve", fields: ["contract_id"] },
	{ name: "pass_production_safety", surface: "safety", group: "record", fields: ["contract_id"] },
	{ name: "record_production_dispatch", surface: "safety", group: "record", fields: ["contract_id"] },
	{ name: "record_observed_production_result", surface: "safety", group: "record", fields: ["contract_id", "observation"] },
	{ name: "reconcile_observed_production_result", surface: "safety", group: "record", fields: ["contract_id"] },
	{ name: "set_production_limit", surface: "safety", group: "record", fields: ["organization_id", "limit"] },
	{ name: "engage_kill_switch", surface: "safety", group: "record", fields: ["contract_id"] },
] as const;
