/** Frozen product UX copy. English is the reference implementation; BG/AR localize the same keys. */

export type ProductLocale = "en" | "bg" | "ar";

export function productLocale(locale: string): ProductLocale {
	if (locale === "bg" || locale === "ar") return locale;
	return "en";
}

export function isRtlLocale(locale: string): boolean {
	return locale === "ar";
}

/** Domain glossary — one term per concept across locales. */
export const glossary = {
	en: {
		intent: "Intent",
		opportunity: "Opportunity",
		match: "Match",
		introduction: "Introduction",
		relationship: "Relationship",
		confidential: "Confidential",
		strongMatch: "Strong match",
	},
	bg: {
		intent: "Намерение",
		opportunity: "Възможност",
		match: "Съвпадение",
		introduction: "Представяне",
		relationship: "Връзка",
		confidential: "Поверително",
		strongMatch: "Силно съвпадение",
	},
	ar: {
		intent: "نية",
		opportunity: "فرصة",
		match: "مطابقة",
		introduction: "تقديم",
		relationship: "علاقة",
		confidential: "سري",
		strongMatch: "مطابقة قوية",
	},
} as const;

export const radarBoardCopy = {
	en: {
		title: "Business Radar",
		lead: "When a compatible opportunity exists, you will see why it fits, what stays confidential, and the next safe step.",
		unavailable: "Radar is not available on this database yet. Apply migration 012.",
		emptyPrimary: "No matches need your action yet.",
		looking:
			"Your Business Intent is active. The system is looking for compatible opportunities — nothing to review yet.",
		startIntent: "Create your first Business Intent",
		emptySecondary: "Nothing here yet.",
		qualify: "Qualify",
		request: "Request introduction",
		accept: "Accept",
		decline: "Decline",
		working: "Working…",
		waiting: "Waiting for the other party to respond.",
		primary: "Needs your action",
		secondary: "Relationships and other facts",
		needsAttention: "need attention",
		relationships: "active relationships",
		opportunities: "open opportunities",
		metaDescription: "Operational view of the matching vertical.",
	},
	bg: {
		title: "Бизнес радар",
		lead: "Когато има съвместима възможност, ще видиш защо пасва, какво остава поверително и кое е следващото безопасно действие.",
		unavailable: "Радарът още не е наличен в тази база. Приложи миграция 012.",
		emptyPrimary: "Няма съвпадения, които чакат действие.",
		looking:
			"Бизнес намерението е активно. Системата търси съвместими възможности — още няма какво да прегледаш.",
		startIntent: "Създай първото бизнес намерение",
		emptySecondary: "Все още няма редове тук.",
		qualify: "Квалифицирай",
		request: "Поискай представяне",
		accept: "Приеми",
		decline: "Откажи",
		working: "Изпълнява се…",
		waiting: "Чака се отговор от другата страна.",
		primary: "Изисква действие",
		secondary: "Връзки и други факти",
		needsAttention: "искат внимание",
		relationships: "активни връзки",
		opportunities: "отворени възможности",
		metaDescription: "Оперативен изглед към matching вертикалата.",
	},
	ar: {
		title: "رادار الأعمال",
		lead: "عندما توجد فرصة متوافقة، سترى سبب الملاءمة، وما يبقى سريًا، والخطوة الآمنة التالية.",
		unavailable: "الرادار غير متاح في هذه القاعدة بعد. طبّق الترحيل 012.",
		emptyPrimary: "لا توجد مطابقات تحتاج إلى إجراء منك بعد.",
		looking: "نية الأعمال نشطة. يبحث النظام عن فرص متوافقة — لا يوجد شيء للمراجعة بعد.",
		startIntent: "أنشئ أول نية أعمال",
		emptySecondary: "لا يوجد شيء هنا بعد.",
		qualify: "تأهيل",
		request: "اطلب تقديمًا",
		accept: "قبول",
		decline: "رفض",
		working: "جارٍ العمل…",
		waiting: "بانتظار رد الطرف الآخر.",
		primary: "يحتاج إلى إجراء منك",
		secondary: "العلاقات وحقائق أخرى",
		needsAttention: "تحتاج إلى انتباه",
		relationships: "علاقات نشطة",
		opportunities: "فرص مفتوحة",
		metaDescription: "عرض تشغيلي لمسار المطابقة.",
	},
} as const;

export const matchCardCopy = {
	en: {
		found: "What we found",
		why: "Why it fits",
		hidden: "What's hidden",
		next: "What to do next",
		fallbackTitle: "Business opportunity",
		goodMatch: "Good match",
		possibleMatch: "Possible match",
		criteriaAlignment: "criteria alignment",
		confidentialBody:
			"The other party stays unnamed until both sides agree to an introduction. This screen does not try to infer identity.",
		reasons: {
			industry_match: "industry alignment",
			target_market_overlap: "target-market overlap",
			kind_compatibility: "compatible business intent",
		},
	},
	bg: {
		found: "Какво открихме",
		why: "Защо пасва",
		hidden: "Какво е скрито",
		next: "Какво да направиш",
		fallbackTitle: "Бизнес възможност",
		goodMatch: "Добро съвпадение",
		possibleMatch: "Възможно съвпадение",
		criteriaAlignment: "съвпадение по критерии",
		confidentialBody:
			"Другата страна остава без име, докато и двете страни не се съгласят на представяне. Екранът не се опитва да разпознае самоличност.",
		reasons: {
			industry_match: "съвпадение по индустрия",
			target_market_overlap: "припокриване на целеви пазари",
			kind_compatibility: "съвместимо бизнес намерение",
		},
	},
	ar: {
		found: "ما وجدناه",
		why: "لماذا يناسب",
		hidden: "ما هو مخفي",
		next: "الخطوة التالية",
		fallbackTitle: "فرصة أعمال",
		goodMatch: "مطابقة جيدة",
		possibleMatch: "مطابقة محتملة",
		criteriaAlignment: "توافق المعايير",
		confidentialBody:
			"يبقى الطرف الآخر دون اسم إلى أن يوافق الجانبان على تقديم. هذه الشاشة لا تحاول استنتاج الهوية.",
		reasons: {
			industry_match: "توافق الصناعة",
			target_market_overlap: "تداخل الأسواق المستهدفة",
			kind_compatibility: "نية أعمال متوافقة",
		},
	},
} as const;

export const onboardingCopy = {
	en: {
		kicker: "Get started",
		title: "Create your first Business Intent",
		lead: "Only what the matcher needs: what you seek or offer, industry, markets, visibility, and a short public-safe description. After you activate, the intent is live. Radar will show a match when a compatible opportunity exists — that is not guaranteed immediately.",
		orgRequired: "Organization required",
		kindLegend: "What are you looking to do?",
		kinds: {
			buy: { label: "Buy", hint: "I am looking for a supply, product, or service." },
			sell: { label: "Sell", hint: "I can offer a supply, product, or service." },
			partner: { label: "Partner", hint: "I want a counterpart to work with." },
		},
		industry: "Industry",
		industryPlaceholder: "e.g. manufacturing",
		markets: "Target markets",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "Country or region codes the matcher uses for overlap.",
		visibility: "Visibility",
		visibilities: {
			confidential: "Confidential — matchable, identity hidden until introduction",
			network: "Network — visible to other organizations",
			public: "Public — listed openly",
		},
		description: "Short description",
		descriptionPlaceholder: "What a counterpart may safely see.",
		descriptionHint: "Keep it public-safe. Confidential details stay hidden until an introduction is accepted.",
		requiredError: "Industry, target markets, and a short description are required.",
		activate: "Activate intent",
		activating: "Activating…",
	},
	bg: {
		kicker: "Начало",
		title: "Създай първото бизнес намерение",
		lead: "Само каквото matcher-ът трябва: какво търсиш или предлагаш, индустрия, пазари, видимост и кратко публично-безопасно описание. След активиране намерението е живо. Радарът ще покаже съвпадение, когато има съвместима възможност — това не е гарантирано веднага.",
		orgRequired: "Нужна е организация",
		kindLegend: "Какво искаш да направиш?",
		kinds: {
			buy: { label: "Купувам", hint: "Търся доставка, продукт или услуга." },
			sell: { label: "Продавам", hint: "Мога да предложа доставка, продукт или услуга." },
			partner: { label: "Партньорство", hint: "Искам насрещна страна, с която да работя." },
		},
		industry: "Индустрия",
		industryPlaceholder: "напр. производство",
		markets: "Целеви пазари",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "Кодове на държави или региони, които matcher-ът ползва за припокриване.",
		visibility: "Видимост",
		visibilities: {
			confidential: "Поверително — може да се съпоставя, самоличността е скрита до представяне",
			network: "Мрежа — видимо за други организации",
			public: "Публично — обявено открито",
		},
		description: "Кратко описание",
		descriptionPlaceholder: "Какво може безопасно да види насрещната страна.",
		descriptionHint: "Дръж го публично-безопасно. Поверителните детайли остават скрити, докато не се приеме представяне.",
		requiredError: "Индустрия, целеви пазари и кратко описание са задължителни.",
		activate: "Активирай намерението",
		activating: "Активира се…",
	},
	ar: {
		kicker: "ابدأ",
		title: "أنشئ أول نية أعمال",
		lead: "فقط ما يحتاجه محرك المطابقة: ما تبحث عنه أو تقدمه، الصناعة، الأسواق، الظهور، ووصف قصير آمن للعرض العام. بعد التفعيل تكون النية نشطة. سيُظهر الرادار مطابقة عند وجود فرصة متوافقة — وهذا غير مضمون فورًا.",
		orgRequired: "المنظمة مطلوبة",
		kindLegend: "ماذا تريد أن تفعل؟",
		kinds: {
			buy: { label: "شراء", hint: "أبحث عن توريد أو منتج أو خدمة." },
			sell: { label: "بيع", hint: "يمكنني تقديم توريد أو منتج أو خدمة." },
			partner: { label: "شراكة", hint: "أريد طرفًا مقابلًا للعمل معه." },
		},
		industry: "الصناعة",
		industryPlaceholder: "مثلًا التصنيع",
		markets: "الأسواق المستهدفة",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "رموز الدول أو المناطق التي يستخدمها محرك المطابقة للتداخل.",
		visibility: "الظهور",
		visibilities: {
			confidential: "سري — قابل للمطابقة، الهوية مخفية حتى التقديم",
			network: "الشبكة — ظاهر للمنظمات الأخرى",
			public: "عام — مدرج بشكل علني",
		},
		description: "وصف قصير",
		descriptionPlaceholder: "ما يمكن للطرف المقابل أن يراه بأمان.",
		descriptionHint: "أبقِه آمنًا للعرض العام. تبقى التفاصيل السرية مخفية حتى قبول التقديم.",
		requiredError: "الصناعة والأسواق المستهدفة والوصف القصير مطلوبة.",
		activate: "تفعيل النية",
		activating: "جارٍ التفعيل…",
	},
} as const;

export const shellCopy = {
	en: {
		daily: "Daily",
		mesh: "Mesh",
		more: "More",
		radar: "Radar",
		start: "Get started",
		intents: "Intents",
		opportunities: "Opportunities",
		ask: "Ask",
		askShort: "Ask",
		chat: "Chat",
		settings: "Settings",
		community: "Community",
		navAria: "Mobile navigation",
		moreTitle: "More",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "Get started", sub: "Create your first Business Intent" },
			{ href: "/dashboard", icon: "◎", label: "Radar", sub: "Candidates, introductions, relationships" },
			{ href: "/dashboard/intents", icon: "◎", label: "Intents", sub: "Structured demand and supply" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "Opportunities", sub: "Manual openings for matching" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "Settings", sub: "Display name" },
			{ href: "/dashboard/ask", icon: "💬", label: "Chat", sub: "Generic assistant" },
			{ href: "/", icon: "🏡", label: "Home", sub: "How matching works" },
		],
	},
	bg: {
		daily: "Дневно",
		mesh: "Мрежа",
		more: "Още",
		radar: "Радар",
		start: "Начало",
		intents: "Намерения",
		opportunities: "Възможности",
		ask: "Питай",
		askShort: "Питай",
		chat: "Чат",
		settings: "Настройки",
		community: "Общност",
		navAria: "Мобилна навигация",
		moreTitle: "Още",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "Начало", sub: "Създай първото бизнес намерение" },
			{ href: "/dashboard", icon: "◎", label: "Радар", sub: "Кандидати, представяния, връзки" },
			{ href: "/dashboard/intents", icon: "◎", label: "Намерения", sub: "Структурирано търсене и предлагане" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "Възможности", sub: "Ръчни отвори за съпоставяне" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "Настройки", sub: "Показвано име" },
			{ href: "/dashboard/ask", icon: "💬", label: "Чат", sub: "Общ асистент" },
			{ href: "/", icon: "🏡", label: "Начало", sub: "Как работи съпоставянето" },
		],
	},
	ar: {
		daily: "يومي",
		mesh: "الشبكة",
		more: "المزيد",
		radar: "الرادار",
		start: "ابدأ",
		intents: "النيات",
		opportunities: "الفرص",
		ask: "اسأل",
		askShort: "اسأل",
		chat: "محادثة",
		settings: "الإعدادات",
		community: "المجتمع",
		navAria: "التنقل للجوال",
		moreTitle: "المزيد",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "ابدأ", sub: "أنشئ أول نية أعمال" },
			{ href: "/dashboard", icon: "◎", label: "الرادار", sub: "مرشحون، تقديمات، علاقات" },
			{ href: "/dashboard/intents", icon: "◎", label: "النيات", sub: "طلب وعرض منظّمان" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "الفرص", sub: "فتحات يدوية للمطابقة" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "الإعدادات", sub: "الاسم المعروض" },
			{ href: "/dashboard/ask", icon: "💬", label: "محادثة", sub: "مساعد عام" },
			{ href: "/", icon: "🏡", label: "الرئيسية", sub: "كيف تعمل المطابقة" },
		],
	},
} as const;

export const listCopy = {
	en: {
		intentsTitle: "Business intents",
		intentsLead:
			"Structured foundation for matching: type, industry, markets, visibility, lifecycle, and confidentiality.",
		newIntent: "New intent",
		noIntents: "No intents for this organization yet.",
		firstIntent: "Create your first Business Intent",
		oppsTitle: "Business opportunities",
		oppsLead: "Manual openings. Matching reads indexed fields only, never a score.",
		newOpp: "New opportunity",
		noOpps: "No opportunities yet.",
	},
	bg: {
		intentsTitle: "Бизнес намерения",
		intentsLead:
			"Структуриран фундамент за съпоставяне: тип, индустрия, пазари, видимост, жизнен цикъл и поверителност.",
		newIntent: "Ново намерение",
		noIntents: "Все още няма намерения за тази организация.",
		firstIntent: "Създай първото намерение",
		oppsTitle: "Бизнес възможности",
		oppsLead: "Ръчно създадени отвори. Съпоставянето чете само индексирани полета, не score.",
		newOpp: "Нова възможност",
		noOpps: "Няма възможности.",
	},
	ar: {
		intentsTitle: "نيات الأعمال",
		intentsLead: "أساس منظّم للمطابقة: النوع، الصناعة، الأسواق، الظهور، دورة الحياة، والسرية.",
		newIntent: "نية جديدة",
		noIntents: "لا توجد نيات لهذه المنظمة بعد.",
		firstIntent: "أنشئ أول نية أعمال",
		oppsTitle: "فرص الأعمال",
		oppsLead: "فتحات يدوية. المطابقة تقرأ الحقول المفهرسة فقط، وليس درجة.",
		newOpp: "فرصة جديدة",
		noOpps: "لا توجد فرص بعد.",
	},
} as const;

export const cutoverCopy = {
	en: {
		navHow: "How it works",
		navRadar: "Open Radar",
		heroLine1: "Say what you are looking for.",
		heroEm: "Meet the other side",
		heroLine2: "only when both agree.",
		subtitle:
			"Confidential business matching: Intent → Opportunity → Match → Introduction → Relationship. Identity stays hidden until both sides request an introduction.",
		badge: "Working name",
		ctaIntent: "Create your first Business Intent",
		ctaRadar: "Open Business Radar",
		stepKicker: "The product",
		steps: [
			{ title: "What are you looking for?", body: "Describe demand or supply as a Business Intent — industry, markets, and a short public-safe description." },
			{ title: "Business Intent", body: "The structured record the matcher reads. Confidential intents can still match; the other party does not see who you are yet." },
			{ title: "Matching", body: "Deterministic criteria alignment — not a deal probability and not a guarantee." },
			{ title: "Business Radar", body: "Your home: candidates, introductions, and relationships in one place." },
			{ title: "Introduction", body: "Both sides must agree before identity is revealed." },
			{ title: "Relationship", body: "After a mutual introduction, the connection is a first-class record — not a leaked profile." },
		],
		finalTitle: "Start with one Business Intent.",
		finalSubtitle: "Radar is the centre of the product. Start with one Intent and watch for matches.",
		footerLine: "Confidential business matching. Working product name — final brand not chosen.",
		footerPrivacy: "Privacy",
		footerLogin: "Sign in",
		footerLegal: "Matching is informational. A strong match is criteria alignment, not a closed deal. Confidential data stays hidden until both sides agree to an introduction.",
		loginKicker: "Sign in",
		loginTitle: "Continue to Radar",
		loginBody: "After sign-in you create a Business Intent, then watch Radar for matches.",
		loginBack: "← Home",
		settingsTitle: "Settings",
		settingsLead: "Display name for this account.",
	},
	bg: {
		navHow: "Как работи",
		navRadar: "Отвори Радара",
		heroLine1: "Кажете какво търсите.",
		heroEm: "Другата страна",
		heroLine2: "се вижда само при взаимно съгласие.",
		subtitle:
			"Поверително бизнес съпоставяне: Намерение → Възможност → Съвпадение → Представяне → Връзка. Идентичността остава скрита, докато и двете страни не поискат представяне.",
		badge: "Работно име",
		ctaIntent: "Създай първото бизнес намерение",
		ctaRadar: "Отвори бизнес радара",
		stepKicker: "Продуктът",
		steps: [
			{ title: "Какво търсите?", body: "Опишете търсене или предлагане като бизнес намерение — индустрия, пазари и кратко описание, безопасно за показване." },
			{ title: "Бизнес намерение", body: "Структурираният запис, който matcher-ът чете. Поверителните намерения също могат да се съпоставят; другата страна още не вижда кой сте." },
			{ title: "Съпоставяне", body: "Детерминирано подреждане по критерии — не вероятност за сделка и не гаранция." },
			{ title: "Бизнес радар", body: "Домът ви: кандидати, представяния и връзки на едно място." },
			{ title: "Представяне", body: "И двете страни трябва да се съгласят, преди да се разкрие идентичност." },
			{ title: "Връзка", body: "След взаимно представяне връзката е отделен запис — не изтекъл профил." },
		],
		finalTitle: "Започнете с едно бизнес намерение.",
		finalSubtitle: "Радарът е центърът на продукта. Започнете с едно намерение и следете съвпаденията.",
		footerLine: "Поверително бизнес съпоставяне. Работно име — окончателната марка още не е избрана.",
		footerPrivacy: "Поверителност",
		footerLogin: "Вход",
		footerLegal: "Съпоставянето е информационно. Силно съвпадение е подреждане по критерии, не сключена сделка. Поверителните данни остават скрити, докато и двете страни не се съгласят на представяне.",
		loginKicker: "Вход",
		loginTitle: "Продължете към Радара",
		loginBody: "След вход създавате бизнес намерение и следите Радара за съвпадения.",
		loginBack: "← Начало",
		settingsTitle: "Настройки",
		settingsLead: "Показвано име за този акаунт.",
	},
	ar: {
		navHow: "كيف يعمل",
		navRadar: "افتح الرادار",
		heroLine1: "قل ما الذي تبحث عنه.",
		heroEm: "الطرف الآخر",
		heroLine2: "يظهر فقط عند موافقة الطرفين.",
		subtitle:
			"مطابقة أعمال سرية: نية → فرصة → مطابقة → تقديم → علاقة. تبقى الهوية مخفية حتى يطلب الطرفان تقديمًا.",
		badge: "اسم مؤقت",
		ctaIntent: "أنشئ أول نية أعمال",
		ctaRadar: "افتح رادار الأعمال",
		stepKicker: "المنتج",
		steps: [
			{ title: "ما الذي تبحث عنه؟", body: "صف الطلب أو العرض كنية أعمال — الصناعة والأسواق ووصف قصير آمن للعرض." },
			{ title: "نية الأعمال", body: "السجل المنظّم الذي يقرأه محرك المطابقة. النيات السرية يمكن أن تُطابق دون كشف هويتك بعد." },
			{ title: "المطابقة", body: "محاذاة معايير حتمية — ليست احتمالية صفقة وليست ضمانًا." },
			{ title: "رادار الأعمال", body: "صفحتك الرئيسية: المرشحون والتقديمات والعلاقات في مكان واحد." },
			{ title: "التقديم", body: "يجب أن يوافق الطرفان قبل كشف الهوية." },
			{ title: "العلاقة", body: "بعد تقديم متبادل تصبح الصلة سجلًا قائمًا بذاته — وليس ملفًا مسرّبًا." },
		],
		finalTitle: "ابدأ بنية أعمال واحدة.",
		finalSubtitle: "الرادار هو مركز المنتج. ابدأ بنية واحدة وتابع المطابقات.",
		footerLine: "مطابقة أعمال سرية. اسم منتج مؤقت — لم يُختر الاسم النهائي.",
		footerPrivacy: "الخصوصية",
		footerLogin: "تسجيل الدخول",
		footerLegal: "المطابقة معلوماتية. المطابقة القوية محاذاة معايير وليست صفقة مكتملة. تبقى البيانات السرية مخفية حتى يوافق الطرفان على التقديم.",
		loginKicker: "تسجيل الدخول",
		loginTitle: "تابع إلى الرادار",
		loginBody: "بعد تسجيل الدخول تنشئ نية أعمال ثم تتابع الرادار بحثًا عن مطابقات.",
		loginBack: "← الرئيسية",
		settingsTitle: "الإعدادات",
		settingsLead: "الاسم المعروض لهذا الحساب.",
	},
} as const;

export function uxCopy<T extends Record<ProductLocale, unknown>>(locale: string, table: T): T[ProductLocale] {
	return table[productLocale(locale)];
}
