/** Frozen product UX copy. English is the reference implementation; BG/AR localize the same keys. */

export type ProductLocale = "en" | "bg" | "ar";

export function productLocale(locale: string): ProductLocale {
	if (locale === "bg" || locale === "ar") return locale;
	return "en";
}

export function isRtlLocale(locale: string): boolean {
	return locale === "ar";
}

/** Domain glossary — one term per concept across locales. */
export const glossary = {
	en: {
		intent: "Intent",
		opportunity: "Opportunity",
		match: "Match",
		introduction: "Introduction",
		relationship: "Relationship",
		confidential: "Confidential",
		strongMatch: "Strong match",
	},
	bg: {
		intent: "Намерение",
		opportunity: "Възможност",
		match: "Съвпадение",
		introduction: "Представяне",
		relationship: "Връзка",
		confidential: "Поверително",
		strongMatch: "Силно съвпадение",
	},
	ar: {
		intent: "نية",
		opportunity: "فرصة",
		match: "مطابقة",
		introduction: "تقديم",
		relationship: "علاقة",
		confidential: "سري",
		strongMatch: "مطابقة قوية",
	},
} as const;

export const radarBoardCopy = {
	en: {
		title: "Business Radar",
		lead: "When a compatible opportunity exists, you will see why it fits, what stays confidential, and the next safe step.",
		unavailable: "Radar is not available on this database yet. Apply migration 012.",
		emptyPrimary: "No matches need your action yet.",
		looking:
			"Your Business Intent is active. The system is looking for compatible opportunities — nothing to review yet.",
		startIntent: "Create your first Business Intent",
		emptySecondary: "Nothing here yet.",
		qualify: "Qualify",
		request: "Request introduction",
		accept: "Accept",
		decline: "Decline",
		working: "Working…",
		waiting: "Waiting for the other party to respond.",
		primary: "Needs your action",
		secondary: "Relationships and other facts",
		needsAttention: "need attention",
		relationships: "active relationships",
		opportunities: "open opportunities",
		metaDescription: "Operational view of the matching vertical.",
	},
	bg: {
		title: "Бизнес радар",
		lead: "Когато има съвместима възможност, ще видиш защо пасва, какво остава поверително и кое е следващото безопасно действие.",
		unavailable: "Радарът още не е наличен в тази база. Приложи миграция 012.",
		emptyPrimary: "Няма съвпадения, които чакат действие.",
		looking:
			"Бизнес намерението е активно. Системата търси съвместими възможности — още няма какво да прегледаш.",
		startIntent: "Създай първото бизнес намерение",
		emptySecondary: "Все още няма редове тук.",
		qualify: "Квалифицирай",
		request: "Поискай представяне",
		accept: "Приеми",
		decline: "Откажи",
		working: "Изпълнява се…",
		waiting: "Чака се отговор от другата страна.",
		primary: "Изисква действие",
		secondary: "Връзки и други факти",
		needsAttention: "искат внимание",
		relationships: "активни връзки",
		opportunities: "отворени възможности",
		metaDescription: "Оперативен изглед към matching вертикалата.",
	},
	ar: {
		title: "رادار الأعمال",
		lead: "عندما توجد فرصة متوافقة، سترى سبب الملاءمة، وما يبقى سريًا، والخطوة الآمنة التالية.",
		unavailable: "الرادار غير متاح في هذه القاعدة بعد. طبّق الترحيل 012.",
		emptyPrimary: "لا توجد مطابقات تحتاج إلى إجراء منك بعد.",
		looking: "نية الأعمال نشطة. يبحث النظام عن فرص متوافقة — لا يوجد شيء للمراجعة بعد.",
		startIntent: "أنشئ أول نية أعمال",
		emptySecondary: "لا يوجد شيء هنا بعد.",
		qualify: "تأهيل",
		request: "اطلب تقديمًا",
		accept: "قبول",
		decline: "رفض",
		working: "جارٍ العمل…",
		waiting: "بانتظار رد الطرف الآخر.",
		primary: "يحتاج إلى إجراء منك",
		secondary: "العلاقات وحقائق أخرى",
		needsAttention: "تحتاج إلى انتباه",
		relationships: "علاقات نشطة",
		opportunities: "فرص مفتوحة",
		metaDescription: "عرض تشغيلي لمسار المطابقة.",
	},
} as const;

export const matchCardCopy = {
	en: {
		found: "What we found",
		why: "Why it fits",
		hidden: "What's hidden",
		next: "What to do next",
		fallbackTitle: "Business opportunity",
		goodMatch: "Good match",
		possibleMatch: "Possible match",
		criteriaAlignment: "criteria alignment",
		confidentialBody:
			"The other party stays unnamed until both sides agree to an introduction. This screen does not try to infer identity.",
		reasons: {
			industry_match: "industry alignment",
			target_market_overlap: "target-market overlap",
			kind_compatibility: "compatible business intent",
		},
	},
	bg: {
		found: "Какво открихме",
		why: "Защо пасва",
		hidden: "Какво е скрито",
		next: "Какво да направиш",
		fallbackTitle: "Бизнес възможност",
		goodMatch: "Добро съвпадение",
		possibleMatch: "Възможно съвпадение",
		criteriaAlignment: "съвпадение по критерии",
		confidentialBody:
			"Другата страна остава без име, докато и двете страни не се съгласят на представяне. Екранът не се опитва да разпознае самоличност.",
		reasons: {
			industry_match: "съвпадение по индустрия",
			target_market_overlap: "припокриване на целеви пазари",
			kind_compatibility: "съвместимо бизнес намерение",
		},
	},
	ar: {
		found: "ما وجدناه",
		why: "لماذا يناسب",
		hidden: "ما هو مخفي",
		next: "الخطوة التالية",
		fallbackTitle: "فرصة أعمال",
		goodMatch: "مطابقة جيدة",
		possibleMatch: "مطابقة محتملة",
		criteriaAlignment: "توافق المعايير",
		confidentialBody:
			"يبقى الطرف الآخر دون اسم إلى أن يوافق الجانبان على تقديم. هذه الشاشة لا تحاول استنتاج الهوية.",
		reasons: {
			industry_match: "توافق الصناعة",
			target_market_overlap: "تداخل الأسواق المستهدفة",
			kind_compatibility: "نية أعمال متوافقة",
		},
	},
} as const;

export const onboardingCopy = {
	en: {
		kicker: "Get started",
		title: "Create your first Business Intent",
		lead: "Only what the matcher needs: what you seek or offer, industry, markets, visibility, and a short public-safe description. After you activate, the intent is live. Radar will show a match when a compatible opportunity exists — that is not guaranteed immediately.",
		orgRequired: "Organization required",
		kindLegend: "What are you looking to do?",
		kinds: {
			buy: { label: "Buy", hint: "I am looking for a supply, product, or service." },
			sell: { label: "Sell", hint: "I can offer a supply, product, or service." },
			partner: { label: "Partner", hint: "I want a counterpart to work with." },
		},
		industry: "Industry",
		industryPlaceholder: "e.g. manufacturing",
		markets: "Target markets",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "Country or region codes the matcher uses for overlap.",
		visibility: "Visibility",
		visibilities: {
			confidential: "Confidential — matchable, identity hidden until introduction",
			network: "Network — visible to other organizations",
			public: "Public — listed openly",
		},
		description: "Short description",
		descriptionPlaceholder: "What a counterpart may safely see.",
		descriptionHint: "Keep it public-safe. Confidential details stay hidden until an introduction is accepted.",
		requiredError: "Industry, target markets, and a short description are required.",
		activate: "Activate intent",
		activating: "Activating…",
	},
	bg: {
		kicker: "Начало",
		title: "Създай първото бизнес намерение",
		lead: "Само каквото matcher-ът трябва: какво търсиш или предлагаш, индустрия, пазари, видимост и кратко публично-безопасно описание. След активиране намерението е живо. Радарът ще покаже съвпадение, когато има съвместима възможност — това не е гарантирано веднага.",
		orgRequired: "Нужна е организация",
		kindLegend: "Какво искаш да направиш?",
		kinds: {
			buy: { label: "Купувам", hint: "Търся доставка, продукт или услуга." },
			sell: { label: "Продавам", hint: "Мога да предложа доставка, продукт или услуга." },
			partner: { label: "Партньорство", hint: "Искам насрещна страна, с която да работя." },
		},
		industry: "Индустрия",
		industryPlaceholder: "напр. производство",
		markets: "Целеви пазари",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "Кодове на държави или региони, които matcher-ът ползва за припокриване.",
		visibility: "Видимост",
		visibilities: {
			confidential: "Поверително — може да се съпоставя, самоличността е скрита до представяне",
			network: "Мрежа — видимо за други организации",
			public: "Публично — обявено открито",
		},
		description: "Кратко описание",
		descriptionPlaceholder: "Какво може безопасно да види насрещната страна.",
		descriptionHint: "Дръж го публично-безопасно. Поверителните детайли остават скрити, докато не се приеме представяне.",
		requiredError: "Индустрия, целеви пазари и кратко описание са задължителни.",
		activate: "Активирай намерението",
		activating: "Активира се…",
	},
	ar: {
		kicker: "ابدأ",
		title: "أنشئ أول نية أعمال",
		lead: "فقط ما يحتاجه محرك المطابقة: ما تبحث عنه أو تقدمه، الصناعة، الأسواق، الظهور، ووصف قصير آمن للعرض العام. بعد التفعيل تكون النية نشطة. سيُظهر الرادار مطابقة عند وجود فرصة متوافقة — وهذا غير مضمون فورًا.",
		orgRequired: "المنظمة مطلوبة",
		kindLegend: "ماذا تريد أن تفعل؟",
		kinds: {
			buy: { label: "شراء", hint: "أبحث عن توريد أو منتج أو خدمة." },
			sell: { label: "بيع", hint: "يمكنني تقديم توريد أو منتج أو خدمة." },
			partner: { label: "شراكة", hint: "أريد طرفًا مقابلًا للعمل معه." },
		},
		industry: "الصناعة",
		industryPlaceholder: "مثلًا التصنيع",
		markets: "الأسواق المستهدفة",
		marketsPlaceholder: "BG, DE, RO",
		marketsHint: "رموز الدول أو المناطق التي يستخدمها محرك المطابقة للتداخل.",
		visibility: "الظهور",
		visibilities: {
			confidential: "سري — قابل للمطابقة، الهوية مخفية حتى التقديم",
			network: "الشبكة — ظاهر للمنظمات الأخرى",
			public: "عام — مدرج بشكل علني",
		},
		description: "وصف قصير",
		descriptionPlaceholder: "ما يمكن للطرف المقابل أن يراه بأمان.",
		descriptionHint: "أبقِه آمنًا للعرض العام. تبقى التفاصيل السرية مخفية حتى قبول التقديم.",
		requiredError: "الصناعة والأسواق المستهدفة والوصف القصير مطلوبة.",
		activate: "تفعيل النية",
		activating: "جارٍ التفعيل…",
	},
} as const;

export const shellCopy = {
	en: {
		daily: "Daily",
		mesh: "Mesh",
		more: "More",
		radar: "Radar",
		intents: "Intents",
		opportunities: "Opportunities",
		ask: "Ask AgriNexus",
		askShort: "Ask",
		chat: "Chat",
		settings: "Settings",
		community: "AI Community",
		navAria: "Mobile navigation",
		moreTitle: "More",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "Get started", sub: "Create your first Business Intent" },
			{ href: "/dashboard", icon: "◎", label: "Radar", sub: "Candidates, introductions, relationships" },
			{ href: "/dashboard/intents", icon: "◎", label: "Intents", sub: "Structured demand and supply" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "Opportunities", sub: "Manual openings for matching" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "Settings", sub: "Organization profile" },
			{ href: "/community", icon: "👥", label: "Community", sub: "Generic core feed" },
			{ href: "/dashboard/ask", icon: "💬", label: "Chat", sub: "Generic LLM runtime" },
			{ href: "/", icon: "🏡", label: "Home", sub: "Public site" },
		],
	},
	bg: {
		daily: "Дневно",
		mesh: "Мрежа",
		more: "Още",
		radar: "Радар",
		intents: "Намерения",
		opportunities: "Възможности",
		ask: "Попитай AgriNexus",
		askShort: "Питай",
		chat: "Чат",
		settings: "Настройки",
		community: "AI общност",
		navAria: "Мобилна навигация",
		moreTitle: "Още",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "Начало", sub: "Създай първото бизнес намерение" },
			{ href: "/dashboard", icon: "◎", label: "Радар", sub: "Кандидати, представяния, връзки" },
			{ href: "/dashboard/intents", icon: "◎", label: "Намерения", sub: "Структурирано търсене и предлагане" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "Възможности", sub: "Ръчни отвори за съпоставяне" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "Настройки", sub: "Профил на организацията" },
			{ href: "/community", icon: "👥", label: "Общност", sub: "Generic core емисия" },
			{ href: "/dashboard/ask", icon: "💬", label: "Чат", sub: "Generic LLM runtime" },
			{ href: "/", icon: "🏡", label: "Начало", sub: "Публичен сайт" },
		],
	},
	ar: {
		daily: "يومي",
		mesh: "الشبكة",
		more: "المزيد",
		radar: "الرادار",
		intents: "النيات",
		opportunities: "الفرص",
		ask: "اسأل AgriNexus",
		askShort: "اسأل",
		chat: "محادثة",
		settings: "الإعدادات",
		community: "مجتمع الذكاء الاصطناعي",
		navAria: "التنقل للجوال",
		moreTitle: "المزيد",
		moreItems: [
			{ href: "/dashboard/onboarding", icon: "◎", label: "ابدأ", sub: "أنشئ أول نية أعمال" },
			{ href: "/dashboard", icon: "◎", label: "الرادار", sub: "مرشحون، تقديمات، علاقات" },
			{ href: "/dashboard/intents", icon: "◎", label: "النيات", sub: "طلب وعرض منظّمان" },
			{ href: "/dashboard/opportunities", icon: "◎", label: "الفرص", sub: "فتحات يدوية للمطابقة" },
			{ href: "/dashboard/settings", icon: "⚙️", label: "الإعدادات", sub: "ملف المنظمة" },
			{ href: "/community", icon: "👥", label: "المجتمع", sub: "تغذية النواة العامة" },
			{ href: "/dashboard/ask", icon: "💬", label: "محادثة", sub: "تشغيل نموذج لغوي عام" },
			{ href: "/", icon: "🏡", label: "الرئيسية", sub: "الموقع العام" },
		],
	},
} as const;

export const listCopy = {
	en: {
		intentsTitle: "Business intents",
		intentsLead:
			"Structured foundation for matching: type, industry, markets, visibility, lifecycle, and confidentiality.",
		newIntent: "New intent",
		noIntents: "No intents for this organization yet.",
		firstIntent: "Create your first Business Intent",
		oppsTitle: "Business opportunities",
		oppsLead: "Manual openings. Matching reads indexed fields only, never a score.",
		newOpp: "New opportunity",
		noOpps: "No opportunities yet.",
	},
	bg: {
		intentsTitle: "Бизнес намерения",
		intentsLead:
			"Структуриран фундамент за съпоставяне: тип, индустрия, пазари, видимост, жизнен цикъл и поверителност.",
		newIntent: "Ново намерение",
		noIntents: "Все още няма намерения за тази организация.",
		firstIntent: "Създай първото намерение",
		oppsTitle: "Бизнес възможности",
		oppsLead: "Ръчно създадени отвори. Съпоставянето чете само индексирани полета, не score.",
		newOpp: "Нова възможност",
		noOpps: "Няма възможности.",
	},
	ar: {
		intentsTitle: "نيات الأعمال",
		intentsLead: "أساس منظّم للمطابقة: النوع، الصناعة، الأسواق، الظهور، دورة الحياة، والسرية.",
		newIntent: "نية جديدة",
		noIntents: "لا توجد نيات لهذه المنظمة بعد.",
		firstIntent: "أنشئ أول نية أعمال",
		oppsTitle: "فرص الأعمال",
		oppsLead: "فتحات يدوية. المطابقة تقرأ الحقول المفهرسة فقط، وليس درجة.",
		newOpp: "فرصة جديدة",
		noOpps: "لا توجد فرص بعد.",
	},
} as const;

export function uxCopy<T extends Record<ProductLocale, unknown>>(locale: string, table: T): T[ProductLocale] {
	return table[productLocale(locale)];
}
